const actionTypes = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAILURE: "FETCH_FAILURE",
  AXIOS_REQUEST: "AXIOS_REQUEST",
  AXIOS_SUCCESS: "AXIOS_SUCCESS",
  AXIOS_FAILURE: "AXIOS_FAILURE",
}

export default actionTypes
